### ISSUE TITLE
Build script doesn't work with the @material/mwc-elements 

### ISSUE THREAD

**Issue by larsgk** [katejeffreys/rollup-test#6] opened 2019-03-29 08:38 UTC
Reproduce:

* Clone repo
* Update lit-element to latest (2.1.0)
* Build and verify that build works (it does ;))
* Add a component e.g. `npm install @material/mwc-button` & import/add in `my-element`
(The element version is 0.5.0)
* Clean and build

Two things happen:

1. the build throws an error:

```
src/index.js → build/index.js...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en#error-this-is-undefined
node_modules/@material/mwc-button/mwc-button.js
1: var __decorate = this && this.__decorate || function (decorators, target, key, desc) {
                    ^
2:   var c = arguments.length,
3:       r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc,
...and 1 other occurrence
```

and 2. the app never renders - but throws an error in the console:

```
util.js:43 Uncaught TypeError: Cannot read property 'appendChild' of null
    at detectEdgePseudoVarBug (util.js:43)
    at supportsCssVariables (util.js:76)
    at ripple-directive.js:26
```

Using the rollup script from `https://open-wc.org/building/building-rollup.html` works with the mwc-elements.

Also, other elements done with `lit-element` work (with this script).

**Comment by larsgk** [comment] 2019-03-29 08:47
Related to https://github.com/material-components/material-components-web-components/issues/257

**Comment by aomarks** [comment] 2019-08-14 20:40
I think this is more-or-less a dupe of https://github.com/material-components/material-components-web-components/issues/257, and I think will be fixed if we switch to typescript's `importHelpers` style of polyfills, instead of using the globally-injected style.

**Closed as completed by aomarks** 2019-08-14 20:40 UTC
